# Generated by Django 4.1.7 on 2023-03-24 08:19

import django.contrib.auth.models
from django.db import migrations
import users.managers


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelManagers(
            name="user",
            managers=[
                ("object", users.managers.UserManager()),
                ("objects", django.contrib.auth.models.UserManager()),
            ],
        ),
    ]
