# Generated by Django 4.1.7 on 2023-03-26 19:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("instagram", "0006_alter_like_publication"),
    ]

    operations = [
        migrations.RemoveField(model_name="subscription", name="deleted_at",),
        migrations.RemoveField(model_name="subscription", name="edited_at",),
        migrations.RemoveField(model_name="subscription", name="is_deleted",),
    ]
