# Generated by Django 4.1.7 on 2023-03-26 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("instagram", "0007_remove_subscription_deleted_at_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="subscription",
            name="deleted_at",
            field=models.DateTimeField(
                default=None, null=True, verbose_name="Дата и время удаления"
            ),
        ),
        migrations.AddField(
            model_name="subscription",
            name="edited_at",
            field=models.DateTimeField(
                auto_now=True, verbose_name="Дата и время редактирования"
            ),
        ),
        migrations.AddField(
            model_name="subscription",
            name="is_deleted",
            field=models.BooleanField(default=False, verbose_name="Удален"),
        ),
    ]
