# Generated by Django 4.1.7 on 2023-03-27 07:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("instagram", "0008_subscription_deleted_at_subscription_edited_at_and_more"),
    ]

    operations = [
        migrations.RemoveField(model_name="subscription", name="created_at",),
        migrations.RemoveField(model_name="subscription", name="deleted_at",),
        migrations.RemoveField(model_name="subscription", name="edited_at",),
        migrations.RemoveField(model_name="subscription", name="is_deleted",),
    ]
