# Generated by Django 4.1.7 on 2023-03-27 20:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("instagram", "0009_remove_subscription_created_at_and_more"),
    ]

    operations = [
        migrations.RemoveField(model_name="comment", name="deleted_at",),
        migrations.RemoveField(model_name="comment", name="is_deleted",),
        migrations.RemoveField(model_name="like", name="deleted_at",),
        migrations.RemoveField(model_name="like", name="edited_at",),
        migrations.RemoveField(model_name="like", name="is_deleted",),
    ]
